# Generated by Django 3.1.3 on 2024-04-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0003_correspondencia_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='NumeroDepartamento',
            field=models.IntegerField(default=0),
        ),
    ]
